SET TERM ^ ;

CREATE PROCEDURE SP_ALTERAR_ENTREGADOR (
    P_ID INTEGER,
    P_NOME VARCHAR(100),
    P_TELEFONE VARCHAR(20),
    P_VEICULO VARCHAR(50),
    P_PLACA VARCHAR(10)
)
AS 
DECLARE VARIABLE V_ID_ENTREGADOR INTEGER;
BEGIN

    V_ID_ENTREGADOR = NEXT VALUE FOR SEQ_ENTREGADOR_ID;


    UPDATE ENTREGADORES SET
    	NOME = :P_NOME, 
    	TELEFONE = :P_TELEFONE, 
    	VEICULO = :P_VEICULO, 
    	PLACA = :P_PLACA
    WHERE ID_ENTREGADOR = :P_ID;

END^

SET TERM ; ^
