CREATE OR ALTER PROCEDURE SP_ALTERAR_CLIENTE (P_ID INTEGER, P_NOME VARCHAR(100), P_CPF VARCHAR(14), P_TELEFONE VARCHAR(20), P_EMAIL VARCHAR(100), P_CEP VARCHAR(10), P_LOGRADOURO VARCHAR(200), P_LOGRADOURO_NUMERO VARCHAR(100), P_CIDADE VARCHAR(100), P_BAIRRO VARCHAR(100))
AS
BEGIN  
    UPDATE CLIENTES
	SET NOME=:P_NOME, CPF=:P_CPF, TELEFONE=:P_TELEFONE, EMAIL=:P_EMAIL, CEP=:P_CEP, LOGRADOURO=:P_LOGRADOURO, LOGRADOURO_NUMERO=:P_LOGRADOURO_NUMERO, CIDADE=:P_CIDADE, BAIRRO=:P_BAIRRO
	WHERE ID_CLIENTE=:P_ID;
END;