SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_ALTERAR_PEDIDO (P_ID INTEGER, P_STATUS VARCHAR(20), P_ID_ENTREGADOR INTEGER)
AS
BEGIN
	IF (:P_STATUS = 'ENTREGUE') THEN
	UPDATE PEDIDOS SET 
		STATUS= :P_STATUS, 
		ID_ENTREGADOR=:P_ID_ENTREGADOR, 
		DATA_ENTREGA=CURRENT_TIMESTAMP 
     WHERE ID_PEDIDO=:P_ID;
    ELSE
    	UPDATE PEDIDOS SET 
		STATUS= :P_STATUS, 
		ID_ENTREGADOR=:P_ID_ENTREGADOR
     WHERE ID_PEDIDO=:P_ID;

END^

SET TERM ; ^

