SET TERM ^ ;

CREATE PROCEDURE SP_INSERIR_PRODUTO (
	P_NOME VARCHAR(100), 
	P_DESCRICAO VARCHAR(255), 
	P_PRECO DECIMAL(10,2), 
	P_ESTOQUE INTEGER, 
	P_CATEGORIA VARCHAR(50), 
	P_SUBCATEGORIA VARCHAR(50),
	P_CODIGO VARCHAR(10), 
	P_DATA_VALIDADE TIMESTAMP,
	P_OBSERVACAO VARCHAR(255)
)
AS 
DECLARE VARIABLE V_ID_PRODUTO INTEGER;
BEGIN

    V_ID_PRODUTO = NEXT VALUE FOR SEQ_PRODUTO_ID;


INSERT INTO PRODUTOS
(ID_PRODUTO, NOME, DESCRICAO, PRECO, ESTOQUE, CATEGORIA, SUBCATEGORIA, DATA_CADASTRO, CODIGO, DATA_VALIDADE, OBSERVACAO)
VALUES(:V_ID_PRODUTO, :P_NOME, :P_DESCRICAO, :P_PRECO, :P_ESTOQUE, :P_CATEGORIA, :P_SUBCATEGORIA, CURRENT_TIMESTAMP, :P_CODIGO, :P_DATA_VALIDADE, :P_OBSERVACAO);

END^

SET TERM ; ^
