SET TERM ^ ;

CREATE PROCEDURE SP_INSERIR_CLIENTE (
    P_NOME VARCHAR(100),
    P_CPF VARCHAR(14),
    P_TELEFONE VARCHAR(20),
    P_EMAIL VARCHAR(100),
    P_CEP VARCHAR(10), 
    P_LOGRADOURO VARCHAR(200), 
    P_LOGRADOURO_NUMERO VARCHAR(100), 
    P_CIDADE VARCHAR(100), 
    P_BAIRRO VARCHAR(100)
)
AS 
DECLARE VARIABLE V_ID_CLIENTE INTEGER;
BEGIN

    V_ID_CLIENTE = NEXT VALUE FOR SEQ_CLIENTE_ID;


    INSERT INTO CLIENTES (
        ID_CLIENTE, NOME, CPF, TELEFONE, EMAIL, DATA_CADASTRO, 
        CEP, LOGRADOURO, LOGRADOURO_NUMERO, CIDADE, BAIRRO
    ) VALUES (
        :V_ID_CLIENTE, :P_NOME, :P_CPF, :P_TELEFONE, :P_EMAIL, CURRENT_TIMESTAMP, 
        :P_CEP, :P_LOGRADOURO, :P_LOGRADOURO_NUMERO, :P_CIDADE, :P_BAIRRO
    );

END^

SET TERM ; ^
